// Generated by scripts/export_results.py from studies/final-benchmark-v1/analysis/final-benchmark-analysis.json. Do not edit by hand.
export const R = {
 "source": "studies/final-benchmark-v1/analysis/final-benchmark-analysis.json",
 "main": [
  {
   "model": "deepseek-v4.1-flash",
   "arm": "80k",
   "valid": "4/4",
   "CMod": 62.3,
   "CiD": 88.3,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 100.0,
   "C2C33": 81.7,
   "C2C50": 60.8,
   "services": 5.2,
   "tokensK": 89.5
  },
  {
   "model": "deepseek-v4.1-flash",
   "arm": "oc",
   "valid": "4/4",
   "CMod": 60.0,
   "CiD": 89.3,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 96.4,
   "C2C33": 79.3,
   "C2C50": 59.0,
   "services": 5.5,
   "tokensK": 156.9
  },
  {
   "model": "deepseek-v4.1-flash",
   "arm": "wf",
   "valid": "4/4",
   "CMod": 57.3,
   "CiD": 92.3,
   "DTP": 54.6,
   "DI": 27.4,
   "BCP": 50.2,
   "C2C10": 93.3,
   "C2C33": 65.2,
   "C2C50": 54.9,
   "services": 6.2,
   "tokensK": 52.4
  },
  {
   "model": "glm-5.2",
   "arm": "80k",
   "valid": "4/4",
   "CMod": 58.2,
   "CiD": 89.9,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 93.8,
   "C2C33": 77.5,
   "C2C50": 57.7,
   "services": 5.8,
   "tokensK": 64.8
  },
  {
   "model": "glm-5.2",
   "arm": "oc",
   "valid": "4/4",
   "CMod": 55.4,
   "CiD": 89.9,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 93.8,
   "C2C33": 72.5,
   "C2C50": 50.2,
   "services": 6.0,
   "tokensK": 94.6
  },
  {
   "model": "glm-5.2",
   "arm": "wf",
   "valid": "4/4",
   "CMod": 62.7,
   "CiD": 89.3,
   "DTP": 65.3,
   "DI": 23.6,
   "BCP": 40.1,
   "C2C10": 96.4,
   "C2C33": 76.8,
   "C2C50": 69.0,
   "services": 5.2,
   "tokensK": 50.4
  },
  {
   "model": "gpt-oss:120b",
   "arm": "80k",
   "valid": "4/4",
   "CMod": 58.2,
   "CiD": 89.9,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 93.8,
   "C2C33": 77.5,
   "C2C50": 57.7,
   "services": 5.8,
   "tokensK": 98.9
  },
  {
   "model": "gpt-oss:120b",
   "arm": "oc",
   "valid": "2/4",
   "CMod": 55.5,
   "CiD": 95.2,
   "DTP": 56.7,
   "DI": 22.5,
   "BCP": 49.0,
   "C2C10": 92.9,
   "C2C33": 66.1,
   "C2C50": 58.9,
   "services": 5.5,
   "tokensK": 43.8
  },
  {
   "model": "gpt-oss:120b",
   "arm": "wf",
   "valid": "4/4",
   "CMod": 63.6,
   "CiD": 87.5,
   "DTP": 55.9,
   "DI": 38.2,
   "BCP": 48.2,
   "C2C10": 100.0,
   "C2C33": 95.0,
   "C2C50": 71.2,
   "services": 4.5,
   "tokensK": 59.0
  },
  {
   "model": "gemma4:31b",
   "arm": "80k",
   "valid": "4/4",
   "CMod": 64.5,
   "CiD": 88.1,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 96.4,
   "C2C33": 82.9,
   "C2C50": 54.9,
   "services": 5.2,
   "tokensK": 62.4
  },
  {
   "model": "gemma4:31b",
   "arm": "oc",
   "valid": "4/4",
   "CMod": 64.5,
   "CiD": 89.3,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 96.4,
   "C2C33": 79.3,
   "C2C50": 54.9,
   "services": 5.2,
   "tokensK": 107.4
  },
  {
   "model": "gemma4:31b",
   "arm": "wf",
   "valid": "4/4",
   "CMod": 66.9,
   "CiD": 85.0,
   "DTP": 68.6,
   "DI": 35.4,
   "BCP": 45.8,
   "C2C10": 100.0,
   "C2C33": 83.8,
   "C2C50": 67.1,
   "services": 4.5,
   "tokensK": 53.0
  }
 ],
 "pairedVs80k": {
  "CMod": {
   "w": 7,
   "t": 3,
   "l": 6,
   "n": 16,
   "delta": 1.84,
   "p": 0.6414,
   "cd": 0.156
  },
  "CiD": {
   "w": 3,
   "t": 10,
   "l": 3,
   "n": 16,
   "delta": -0.54,
   "p": 0.9576,
   "cd": -0.055
  },
  "DTP": {
   "w": 2,
   "t": 9,
   "l": 5,
   "n": 16,
   "delta": -6.96,
   "p": 0.1959,
   "cd": -0.109
  },
  "DI": {
   "w": 8,
   "t": 6,
   "l": 2,
   "n": 16,
   "delta": 8.71,
   "p": 0.0647,
   "cd": 0.125
  },
  "BCP": {
   "w": 6,
   "t": 6,
   "l": 4,
   "n": 16,
   "delta": 2.79,
   "p": 0.3626,
   "cd": 0.094
  },
  "C2C10": {
   "w": 3,
   "t": 11,
   "l": 2,
   "n": 16,
   "delta": 1.45,
   "p": 0.687,
   "cd": 0.027
  },
  "C2C33": {
   "w": 5,
   "t": 5,
   "l": 6,
   "n": 16,
   "delta": 0.3,
   "p": 0.8153,
   "cd": 0.0
  },
  "C2C50": {
   "w": 9,
   "t": 3,
   "l": 4,
   "n": 16,
   "delta": 7.79,
   "p": 0.1205,
   "cd": 0.277
  },
  "tokens": {
   "w": 0,
   "t": 0,
   "l": 16,
   "n": 16,
   "delta": -25.19,
   "p": 0.0,
   "cd": -0.562
  }
 },
 "pairedVsOC": {
  "CMod": {
   "w": 6,
   "t": 2,
   "l": 6,
   "n": 14,
   "delta": 2.77,
   "p": 0.572,
   "cd": 0.179
  },
  "CiD": {
   "w": 2,
   "t": 8,
   "l": 4,
   "n": 14,
   "delta": -1.05,
   "p": 0.4805,
   "cd": -0.092
  },
  "DTP": {
   "w": 2,
   "t": 7,
   "l": 5,
   "n": 14,
   "delta": -8.31,
   "p": 0.171,
   "cd": -0.133
  },
  "DI": {
   "w": 7,
   "t": 5,
   "l": 2,
   "n": 14,
   "delta": 6.34,
   "p": 0.1147,
   "cd": 0.117
  },
  "BCP": {
   "w": 6,
   "t": 5,
   "l": 3,
   "n": 14,
   "delta": 2.89,
   "p": 0.2561,
   "cd": 0.082
  },
  "C2C10": {
   "w": 4,
   "t": 9,
   "l": 1,
   "n": 14,
   "delta": 1.91,
   "p": 0.2707,
   "cd": 0.102
  },
  "C2C33": {
   "w": 6,
   "t": 3,
   "l": 5,
   "n": 14,
   "delta": 1.89,
   "p": 0.7772,
   "cd": 0.046
  },
  "C2C50": {
   "w": 8,
   "t": 1,
   "l": 5,
   "n": 14,
   "delta": 8.91,
   "p": 0.1976,
   "cd": 0.25
  },
  "tokens": {
   "w": 1,
   "t": 0,
   "l": 13,
   "n": 14,
   "delta": -56.63,
   "p": 0.0004,
   "cd": -0.735
  }
 },
 "ablation": {
  "CMod": {
   "delta": 7.6,
   "w": 13,
   "l": 0,
   "p": 0.0007,
   "n": 24
  },
  "CiD": {
   "delta": 1.59,
   "w": 6,
   "l": 0,
   "p": 0.052,
   "n": 24
  },
  "DTP": {
   "delta": 4.26,
   "w": 6,
   "l": 4,
   "p": 0.3875,
   "n": 24
  },
  "DI": {
   "delta": 10.81,
   "w": 12,
   "l": 0,
   "p": 0.0013,
   "n": 24
  },
  "BCP": {
   "delta": 2.4,
   "w": 8,
   "l": 4,
   "p": 0.1916,
   "n": 24
  },
  "C2C10": {
   "delta": 0.0,
   "w": 0,
   "l": 0,
   "p": null,
   "n": 24
  },
  "C2C33": {
   "delta": -4.9,
   "w": 1,
   "l": 7,
   "p": 0.0752,
   "n": 24
  },
  "C2C50": {
   "delta": 13.89,
   "w": 7,
   "l": 0,
   "p": 0.0281,
   "n": 24
  },
  "services": {
   "delta": -0.5,
   "w": 0,
   "l": 6,
   "p": 0.0518,
   "n": 24
  }
 },
 "vsTools": [
  {
   "arm": "tools",
   "CMod": 62.9,
   "CiD": 64.3,
   "DTP": 62.7,
   "DI": 35.0,
   "BCP": 40.4,
   "C2C10": 94.5,
   "C2C33": 57.4,
   "C2C50": 28.3
  },
  {
   "arm": "80k",
   "CMod": 60.8,
   "CiD": 89.0,
   "DTP": 68.1,
   "DI": 22.4,
   "BCP": 43.3,
   "C2C10": 96.0,
   "C2C33": 79.9,
   "C2C50": 57.8
  },
  {
   "arm": "wf",
   "CMod": 62.6,
   "CiD": 88.5,
   "DTP": 61.1,
   "DI": 31.1,
   "BCP": 46.1,
   "C2C10": 97.4,
   "C2C33": 80.2,
   "C2C50": 65.6
  }
 ],
 "stability": [
  {
   "arm": "80k",
   "demo": 4,
   "jpetstore": 2,
   "partsunlimited": 2,
   "spring-petclinic": 3,
   "mean": 2.75,
   "nvi": 0.0406
  },
  {
   "arm": "oc",
   "demo": 5,
   "jpetstore": 1,
   "partsunlimited": 1,
   "spring-petclinic": 2,
   "mean": 2.25,
   "nvi": 0.026
  },
  {
   "arm": "wf",
   "demo": 5,
   "jpetstore": 2,
   "partsunlimited": 3,
   "spring-petclinic": 2,
   "mean": 3,
   "nvi": 0.0442
  }
 ],
 "convergence": {
  "demo": {
   "all": 10,
   "k80": 3,
   "wf": 4,
   "wfEq80k": 0
  },
  "jpetstore": {
   "all": 5,
   "k80": 1,
   "wf": 4,
   "wfEq80k": 0
  },
  "partsunlimited": {
   "all": 5,
   "k80": 1,
   "wf": 3,
   "wfEq80k": 0
  },
  "spring-petclinic": {
   "all": 6,
   "k80": 2,
   "wf": 2,
   "wfEq80k": 0
  }
 },
 "refiner": {
  "runsWithMoves": 8,
  "runs": 16,
  "delta": {
   "CMod": 4.74,
   "CiD": 3.33,
   "DTP": -4.34,
   "DI": 2.67,
   "BCP": -1.15,
   "C2C10": 0.0,
   "C2C33": -8.75,
   "C2C50": 6.25
  }
 },
 "validity": {
  "80k": {
   "valid": 32,
   "n": 32
  },
  "oc": {
   "valid": 30,
   "n": 32
  },
  "wf": {
   "valid": 32,
   "n": 32
  }
 },
 "invalid": [
  {
   "model": "gpt-oss:120b",
   "system": "partsunlimited",
   "services": 1,
   "missing": [],
   "violations": [
    "too-few-services"
   ]
  },
  {
   "model": "gpt-oss:120b",
   "system": "spring-petclinic",
   "services": 3,
   "missing": [
    "BaseEntity",
    "NamedEntity",
    "Person"
   ],
   "violations": []
  }
 ],
 "stages": {
  "evidence": {
   "tokens": 28989,
   "share": 0.517
  },
  "domain": {
   "tokens": 7330,
   "share": 0.131
  },
  "candidate_generation": {
   "tokens": 19713,
   "share": 0.352
  }
 }
}
